[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

; *******************************************************************
; Note: Default password for endpoints (100-500) is 27837325
; (spells 'ASTEREAL' on a telephone keypad: 2-7-8-3-7-3-2-5)
; *******************************************************************

; --> SIP ACCOUNT FOR 100
[100]
type=endpoint
context=from-internal
transport=transport-udp
disallow=all
allow=ulaw
auth=100
aors=100

[100]
type=auth
auth_type=userpass
password=27837325
username=100

[100]
type=aor
max_contacts=1

; --> SIP ACCOUNT FOR 200
[200]
type=endpoint
context=from-internal
transport=transport-udp
disallow=all
allow=ulaw
auth=200
aors=200

[200]
type=auth
auth_type=userpass
password=27837325
username=200

[200]
type=aor
max_contacts=1

; --> SIP ACCOUNT FOR 300
[300]
type=endpoint
context=from-internal
transport=transport-udp
disallow=all
allow=ulaw
auth=300
aors=300

[300]
type=auth
auth_type=userpass
password=27837325
username=300

[300]
type=aor
max_contacts=1

; --> SIP ACCOUNT FOR 400
[400]
type=endpoint
context=from-internal
transport=transport-udp
disallow=all
allow=ulaw
auth=400
aors=400

[400]
type=auth
auth_type=userpass
password=27837325
username=400

[400]
type=aor
max_contacts=1

; --> SIP ACCOUNT FOR 500
[500]
type=endpoint
context=from-internal
transport=transport-udp
disallow=all
allow=ulaw
auth=500
aors=500

[500]
type=auth
auth_type=userpass
password=27837325
username=500

[500]
type=aor
max_contacts=1

; ************************
; OUTGOING ENDPOINT
; ************************
[outgoing]
type=identify
endpoint=outgoing
match=0.0.0.0

[outgoing]
type=endpoint
context=outgoing
disallow=all
allow=ulaw
;rtp_symmetric=yes
force_rport=yes
;rewrite_contact=yes
language=en
aors=outgoing
t38_udptl=yes
t38_udptl_ec=none
;allow_transfer=yes
transport=transport-udp

[outgoing]
type=aor
remove_existing=yes

; ************************
; END OUTGOING ENDPOINT
; ************************

; ************************
; PABX ENDPOINT
; ************************
[pbx]
type=identify
endpoint=pbx
match=0.0.0.0

[pbx]
type=endpoint
context=internal
disallow=all
allow=ulaw
aors=pbx

[pbx]
type=aor
contact=sip:0.0.0.0:5060
; ************************
; END PABX ENDPOINT
; ************************

; ************************
; IDENTIFY ENDPOINT
; ************************
[anonymous]
type=endpoint
context=default
disallow=all
allow=ulaw
; ************************
; END IDENTIFY ENDPOINT
; ************************
